name: Trigger Chrome UI testing
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0

      - name: Set up Chrome WebDriver
        uses: nanasess/setup-chromedriver@v2.2.1
        with:
          chromedriver-version: '120.0.6099.71'

      - name: Execute Gradle build
        run: ./gradlew test -DCI_JOB_ID=${{ github.run_id }} --scan

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-reports
          path: build/reports/
